recomendations =     ["Cenário desfavorável, Muito baixo desempenho dos indicadores",
                      "Cenário desfavorável, Baixo desempenho dos indicadores",
                      "Cenário desfavorável, Médio desempenho dos indicadores",
                      "Cenário desfavorável, Alto desempenho dos indicadores",
                      "Cenário propício, Muito baixo desempenho dos indicadores",
                      "Cenário propício, Baixo desempenho dos indicadores",
                      "Cenário propício, Médio desempenho dos indicadores",
                      "Cenário propício, Alto desempenho dos indicadores",
                      "Cenário muito favorável, Muito baixo desempenho dos indicadores",
                      "Cenário muito favorável, Baixo desempenho dos indicadores",
                      "Cenário muito favorável, Médio desempenho dos indicadores",
                      "Cenário muito favorável, Alto desempenho dos indicadores"]

def attrs = widgetAttrs['tabs']
attrs.labels = ['tab_0': 'Scenario', 'tab_1': 'Report']

tabs(attrs, ['tab_0': [['widget': 'paragraph', attrs: [text: '**Avaliação da sustentabilidade**']],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Indicadores Ambientais**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':EnvironmentalIndicator']],
                       ['widget': 'paragraph', attrs: [text: 'Índice ambiental: '+ scenario['environment']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Indicadores Econômicos**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':EconomicIndicator']],
                       ['widget': 'paragraph', attrs: [text: 'Índice econômico: '+ scenario['economic']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Indicadores Sociais**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':SocialIndicator']],
                       ['widget': 'paragraph', attrs: [text: 'Índice social: '+ scenario['social']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Avaliação da sustentabilidade**']],
                       ['widget': 'paragraph', attrs: [text: 'Índice da sustentabilidade: '+ scenario['sustainability']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Eficiência da produção**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor'], data: dataReader.':ProductionEfficiencyFeature']],
                       ['widget': 'paragraph', attrs: [text: 'Índice de eficiência da produção: '+ scenario['cost_production_efficiency']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Eficiência tecnológica no campo**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weightTypeLabel': 'Peso cadastrado', 'weight': 'Peso'], data: dataReader.':TechnologicalEfficiencyInTheField']],
                       ['widget': 'paragraph', attrs: [text: 'Índice de tecnológica no campo: '+ scenario['technologicalEfficiencyInTheField']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Eficiência tecnológica na industria**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weightTypeLabel': 'Peso cadastrado', 'weight': 'Peso'], data: dataReader.':TechnologicalEfficiencyInTheIndustrial']],
                       ['widget': 'paragraph', attrs: [text: 'Índice de tecnológica na industria: '+ scenario['technologicalEfficiencyInTheIndustrial']]],
                       ['widget': 'linebreak'],
                       ['widget': 'paragraph', attrs: [text: '**Avaliação da eficiência**']],
                       ['widget': 'paragraph', attrs: [text: 'Índice da eficiência: '+ scenario['efficiency']]],
                       ['widget': 'linebreak']],
             'tab_1': [['widget': 'matrixWithSummary',  attrs:  [x: scenario['sustainability'],
                                                                 y: scenario['efficiency'],
                                                                 label_x: 'Indice da sustentabilidade',
                                                                 label_y: 'Indice de eficiência',
                                                                 range_x: [-50,150],
                                                                 range_y: [-30,60],
                                                                 quadrants: [4,3],
                                                                 recomendations: recomendations]],
                       ['widget': 'paragraph', attrs: [text: '**Mapa da microregião**']],
                       ['widget': 'map',       attrs: [url: dataReader.'Microregion'.map()]]]
        ], uri)