def attrs = widgetAttrs['tabs']
attrs.labels = ['tab_0': 'Scenario', 'tab_1': 'Report']

tabs(attrs, ['tab_0': [['widget': 'textFormat', attrs: [text: '**Avaliação da sustentabilidade**']],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Indicadores Ambientais**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':EnvironmentalIndicator']],
                       ['widget': 'textFormat', attrs: [text: 'Índice ambiental: '+ scenario['environment']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Indicadores Econômicos**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':EconomicIndicator']],
                       ['widget': 'textFormat', attrs: [text: 'Índice econômico: '+ scenario['economic']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Indicadores Sociais**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weight': 'Peso'], data: dataReader.':SocialIndicator']],
                       ['widget': 'textFormat', attrs: [text: 'Índice social: '+ scenario['social']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Avaliação da sustentabilidade**']],
                       ['widget': 'textFormat', attrs: [text: 'Índice da sustentabilidade: '+ scenario['sustainability']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Eficiência da produção**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor'], data: dataReader.':ProductionEfficiencyFeature']],
                       ['widget': 'textFormat', attrs: [text: 'Índice de eficiência da produção: '+ scenario['cost_production_efficiency']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Eficiência tecnológica no campo**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weightTypeLabel': 'Peso cadastrado', 'weight': 'Peso'], data: dataReader.':TechnologicalEfficiencyInTheField']],
                       ['widget': 'textFormat', attrs: [text: 'Índice de tecnológica no campo: '+ scenario['technologicalEfficiencyInTheField']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Eficiência tecnológica na industria**']],
                       ['widget': 'table',     attrs: [header: ['label': 'Indicador', 'valueTypeLabel': 'Valor cadastrado', 'value': 'Valor', 'weightTypeLabel': 'Peso cadastrado', 'weight': 'Peso'], data: dataReader.':TechnologicalEfficiencyInTheIndustrial']],
                       ['widget': 'textFormat', attrs: [text: 'Índice de tecnológica na industria: '+ scenario['technologicalEfficiencyInTheIndustrial']]],
                       ['widget': 'ln'],
                       ['widget': 'textFormat', attrs: [text: '**Avaliação da eficiência**']],
                       ['widget': 'textFormat', attrs: [text: 'Índice da eficiência: '+ scenario['efficiency']]],
                       ['widget': 'ln']],
             'tab_1': formulaView
        ], uri)