#!/bin/bash
# SustenAgro
#
# description: blazegraph and web system execution

case $1 in
    start)
        /bin/bash /www/sustenagro/sustenagro-start.sh
    ;;
    stop)
        /bin/bash /www/sustenagro/sustenagro-stop.sh
    ;;
    restart)
        /bin/bash /www/sustenagro/sustenagro-stop.sh
        /bin/bash /www/sustenagro/sustenagro-start.sh
;;
esac
exit 0
